### ISSUE TITLE
asking for help with dataset

### ISSUE THREAD

**Issue by GoldenAbel** [lynx97/laplacian_classify_recapture_image#1]
学习和测试数据，希望大神借一下，研究研究，jinntaoo@sina.com , 万分感激

**Comment by lynx97** [comment]
you can download from http://rose1.ntu.edu.sg/datasets/recapturedImages.asp

> 学习和测试数据，希望大神借一下，研究研究，[jinntaoo@sina.com](mailto:jinntaoo@sina.com) , 万分感激
